on:
  push:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out
        uses: actions/checkout@v4.1.7
      - name: Set Up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'
      - name: Install Dependencies
        run: |
          python -m venv venv
          venv/bin/pip install -r requirements.txt
      - name: Connect to WireGuard
        run: |
          sudo apt-get install -y wireguard
          echo "${{ secrets.WG_PRIVATE_KEY }}" > /tmp/wg-key
          chmod 600 /tmp/wg-key
          sudo ip link add wg0 type wireguard
          sudo wg set wg0 \
            private-key /tmp/wg-key \
            peer ${{ secrets.WG_SERVER_PUBKEY }} \
            endpoint ${{ secrets.ARTIFACT_HOST }}:51821 \
            allowed-ips 10.10.10.100/32
          sudo ip addr add 10.10.10.102/32 dev wg0
          sudo ip link set wg0 up
          sudo ip route add 10.10.10.100/32 dev wg0
          rm /tmp/wg-key
      - name: Upload to server
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.ARTIFACT_SSH_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519    
          sudo wg show
          nc -zv 10.10.10.100 22
          ssh-keyscan -v 10.10.10.100 >> ~/.ssh/known_host
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=no spotify-data-tool@10.10.10.100 which rsync
          rsync -e "ssh -v" -zpr --delete \
             --include='main.py' \
             --include='src/' \
             --include='src/**' \
             --include='static/' \
             --include='static/**' \
             --include='venv/' \
             --include='venv/**' \
             --exclude='*' \
             . spotify-data-tool@10.10.10.100:/opt/spotify-data-tool/
      - name: Deployed
        run: |
          echo 🎉🎉🎉🎉